version: "3"

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "1337:80"
    links:
      - notifications
      - gateway
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    network_mode: bridge
  notifications:
    build:
      context: ./notifications
      dockerfile: Dockerfile
    image: notifications
    container_name: notifications
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_CONNECTION_STRING=$MONGO_CONNECTION_STRING
      - SENDGRID_API_KEY=$SENDGRID_API_KEY
      - MAILGUN_API_KEY=$MAILGUN_API_KEY
      - TWILLIO_AUTH_TOKEN=$TWILLIO_AUTH_TOKEN
      - TWILLIO_API_KEY=$TWILLIO_API_KEY
      - TWILLIO_SID=$TWILLIO_SID
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./comments:/usr/src/app
      - /usr/src/app/node_modules
    network_mode: bridge
  gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: gateway
    container_name: gateway
    restart: unless-stopped
    env_file: .env
    links:
      - notifications
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - ./api-gateway:/usr/src/app
      - /usr/src/app/node_modules
    network_mode: bridge
